/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuditoriaIaRouteImport } from './routes/auditoria-ia'
import { Route as ConformidadeRouteImport } from './routes/conformidade'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaIaRoute = AuditoriaIaRouteImport.update({
  id: '/auditoria-ia',
  path: '/auditoria-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformidadeRoute = ConformidadeRouteImport.update({
  id: '/conformidade',
  path: '/conformidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria-ia': typeof AuditoriaIaRoute
  '/conformidade': typeof ConformidadeRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria-ia': typeof AuditoriaIaRoute
  '/conformidade': typeof ConformidadeRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria-ia': typeof AuditoriaIaRoute
  '/conformidade': typeof ConformidadeRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/alertas' | '/auditoria-ia' | '/conformidade' | '/monitoramento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alertas' | '/auditoria-ia' | '/conformidade' | '/monitoramento'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/auditoria-ia'
    | '/conformidade'
    | '/monitoramento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AuditoriaIaRoute: typeof AuditoriaIaRoute
  ConformidadeRoute: typeof ConformidadeRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria-ia': {
      id: '/auditoria-ia'
      path: '/auditoria-ia'
      fullPath: '/auditoria-ia'
      preLoaderRoute: typeof AuditoriaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformidade': {
      id: '/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof ConformidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AuditoriaIaRoute: AuditoriaIaRoute,
  ConformidadeRoute: ConformidadeRoute,
  MonitoramentoRoute: MonitoramentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
