/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAuditoriaIaRouteImport } from './routes/_authenticated/auditoria-ia'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConformidadeRouteImport } from './routes/_authenticated/conformidade'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMonitoramentoRouteImport } from './routes/_authenticated/monitoramento'
import { Route as AuthenticatedPoliticasRouteImport } from './routes/_authenticated/politicas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'

const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/_authenticated/administracao',
    path: '/administracao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/_authenticated/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaIaRoute =
  AuthenticatedAuditoriaIaRouteImport.update({
    id: '/_authenticated/auditoria-ia',
    path: '/auditoria-ia',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConformidadeRoute =
  AuthenticatedConformidadeRouteImport.update({
    id: '/_authenticated/conformidade',
    path: '/conformidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMonitoramentoRoute =
  AuthenticatedMonitoramentoRouteImport.update({
    id: '/_authenticated/monitoramento',
    path: '/monitoramento',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPoliticasRoute = AuthenticatedPoliticasRouteImport.update({
  id: '/_authenticated/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/auditoria-ia': typeof AuthenticatedAuditoriaIaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/politicas': typeof AuthenticatedPoliticasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/auditoria-ia': typeof AuthenticatedAuditoriaIaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/politicas': typeof AuthenticatedPoliticasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/auditoria-ia': typeof AuthenticatedAuditoriaIaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conformidade': typeof AuthenticatedConformidadeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/_authenticated/politicas': typeof AuthenticatedPoliticasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/administracao'
    | '/alertas'
    | '/auditoria-ia'
    | '/configuracoes'
    | '/conformidade'
    | '/dashboard'
    | '/monitoramento'
    | '/politicas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/administracao'
    | '/alertas'
    | '/auditoria-ia'
    | '/configuracoes'
    | '/conformidade'
    | '/dashboard'
    | '/monitoramento'
    | '/politicas'
    | '/relatorios'
  id:
    | '__root__'
    | '/_authenticated/administracao'
    | '/_authenticated/alertas'
    | '/_authenticated/auditoria-ia'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conformidade'
    | '/_authenticated/dashboard'
    | '/_authenticated/monitoramento'
    | '/_authenticated/politicas'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAuditoriaIaRoute: typeof AuthenticatedAuditoriaIaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConformidadeRoute: typeof AuthenticatedConformidadeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMonitoramentoRoute: typeof AuthenticatedMonitoramentoRoute
  AuthenticatedPoliticasRoute: typeof AuthenticatedPoliticasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria-ia': {
      id: '/_authenticated/auditoria-ia'
      path: '/auditoria-ia'
      fullPath: '/auditoria-ia'
      preLoaderRoute: typeof AuthenticatedAuditoriaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conformidade': {
      id: '/_authenticated/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof AuthenticatedConformidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/monitoramento': {
      id: '/_authenticated/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof AuthenticatedMonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/politicas': {
      id: '/_authenticated/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof AuthenticatedPoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAuditoriaIaRoute: AuthenticatedAuditoriaIaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConformidadeRoute: AuthenticatedConformidadeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMonitoramentoRoute: AuthenticatedMonitoramentoRoute,
  AuthenticatedPoliticasRoute: AuthenticatedPoliticasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
