/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuditoriaIaRouteImport } from './routes/auditoria-ia'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConformidadeRouteImport } from './routes/conformidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
=======
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAnaliseRouteImport } from './routes/_authenticated/analise'
import { Route as AuthenticatedAuditoriaIaRouteImport } from './routes/_authenticated/auditoria-ia'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConformidadeRouteImport } from './routes/_authenticated/conformidade'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMonitoramentoRouteImport } from './routes/_authenticated/monitoramento'
import { Route as AuthenticatedPoliticasRouteImport } from './routes/_authenticated/politicas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnaliseRoute = AuthenticatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaIaRoute =
  AuthenticatedAuditoriaIaRouteImport.update({
    id: '/auditoria-ia',
    path: '/auditoria-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConformidadeRoute =
  AuthenticatedConformidadeRouteImport.update({
    id: '/conformidade',
    path: '/conformidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
<<<<<<< HEAD
const ConformidadeRoute = ConformidadeRouteImport.update({
  id: '/conformidade',
  path: '/conformidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasRoute = PoliticasRouteImport.update({
=======
const AuthenticatedMonitoramentoRoute =
  AuthenticatedMonitoramentoRouteImport.update({
    id: '/monitoramento',
    path: '/monitoramento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliticasRoute = AuthenticatedPoliticasRouteImport.update({
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/administracao': typeof AdministracaoRoute
  '/alertas': typeof AlertasRoute
  '/auditoria-ia': typeof AuditoriaIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conformidade': typeof ConformidadeRoute
  '/login': typeof LoginRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/politicas': typeof PoliticasRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/alertas': typeof AlertasRoute
  '/auditoria-ia': typeof AuditoriaIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conformidade': typeof ConformidadeRoute
  '/login': typeof LoginRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/politicas': typeof PoliticasRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
=======
  '/auth': typeof AuthRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/auditoria-ia': typeof AuthenticatedAuditoriaIaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/politicas': typeof AuthenticatedPoliticasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/auditoria-ia': typeof AuthenticatedAuditoriaIaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/politicas': typeof AuthenticatedPoliticasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/administracao': typeof AdministracaoRoute
  '/alertas': typeof AlertasRoute
  '/auditoria-ia': typeof AuditoriaIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conformidade': typeof ConformidadeRoute
  '/login': typeof LoginRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/politicas': typeof PoliticasRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
=======
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/analise': typeof AuthenticatedAnaliseRoute
  '/_authenticated/auditoria-ia': typeof AuthenticatedAuditoriaIaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conformidade': typeof AuthenticatedConformidadeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/_authenticated/politicas': typeof AuthenticatedPoliticasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administracao'
    | '/alertas'
    | '/analise'
    | '/auditoria-ia'
    | '/configuracoes'
    | '/conformidade'
<<<<<<< HEAD
    | '/login'
=======
    | '/dashboard'
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
    | '/monitoramento'
    | '/politicas'
    | '/relatorios'
    | '/simulacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administracao'
    | '/alertas'
    | '/analise'
    | '/auditoria-ia'
    | '/configuracoes'
    | '/conformidade'
<<<<<<< HEAD
    | '/login'
=======
    | '/dashboard'
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
    | '/monitoramento'
    | '/politicas'
    | '/relatorios'
    | '/simulacao'
  id:
    | '__root__'
    | '/'
<<<<<<< HEAD
    | '/administracao'
    | '/alertas'
    | '/auditoria-ia'
    | '/configuracoes'
    | '/conformidade'
    | '/login'
    | '/monitoramento'
    | '/politicas'
    | '/relatorios'
    | '/simulacao'
=======
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administracao'
    | '/_authenticated/alertas'
    | '/_authenticated/analise'
    | '/_authenticated/auditoria-ia'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conformidade'
    | '/_authenticated/dashboard'
    | '/_authenticated/monitoramento'
    | '/_authenticated/politicas'
    | '/_authenticated/relatorios'
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  AdministracaoRoute: typeof AdministracaoRoute
  AlertasRoute: typeof AlertasRoute
  AuditoriaIaRoute: typeof AuditoriaIaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConformidadeRoute: typeof ConformidadeRoute
  LoginRoute: typeof LoginRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  PoliticasRoute: typeof PoliticasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SimulacaoRoute: typeof SimulacaoRoute
=======
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise': {
      id: '/_authenticated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AuthenticatedAnaliseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria-ia': {
      id: '/_authenticated/auditoria-ia'
      path: '/auditoria-ia'
      fullPath: '/auditoria-ia'
      preLoaderRoute: typeof AuthenticatedAuditoriaIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conformidade': {
      id: '/_authenticated/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof AuthenticatedConformidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
=======
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoramento': {
      id: '/_authenticated/monitoramento'
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof AuthenticatedMonitoramentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/politicas': {
      id: '/_authenticated/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof AuthenticatedPoliticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAnaliseRoute: typeof AuthenticatedAnaliseRoute
  AuthenticatedAuditoriaIaRoute: typeof AuthenticatedAuditoriaIaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConformidadeRoute: typeof AuthenticatedConformidadeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMonitoramentoRoute: typeof AuthenticatedMonitoramentoRoute
  AuthenticatedPoliticasRoute: typeof AuthenticatedPoliticasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAnaliseRoute: AuthenticatedAnaliseRoute,
  AuthenticatedAuditoriaIaRoute: AuthenticatedAuditoriaIaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConformidadeRoute: AuthenticatedConformidadeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMonitoramentoRoute: AuthenticatedMonitoramentoRoute,
  AuthenticatedPoliticasRoute: AuthenticatedPoliticasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  AdministracaoRoute: AdministracaoRoute,
  AlertasRoute: AlertasRoute,
  AuditoriaIaRoute: AuditoriaIaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConformidadeRoute: ConformidadeRoute,
  LoginRoute: LoginRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  PoliticasRoute: PoliticasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SimulacaoRoute: SimulacaoRoute,
=======
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
>>>>>>> bdcc283be2bd08ac2c144de4e712415dd4bdd19e
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
